import React, { useState, useRef, useEffect } from 'react';
import {
  FileText, Plus, Eye, X, Search, RotateCcw,
  Loader2, AlertCircle, CheckCircle, XCircle, Clock, AlertTriangle,
  Download, Upload, Calendar, Pencil, Trash2, ChevronDown, ExternalLink
} from 'lucide-react';
import {
  useVehicleDocuments,
  useCreateVehicleDocument,
  useUpdateVehicleDocument,
  useDeleteVehicleDocument,
  useVehicleDocument,
} from '../../../queries/vehicles/vehicleInfoQuery';
import { useVehicles } from '../../../queries/vehicles/vehicleQuery';
import {
  Badge, InfoCard, SectionHeader, EmptyState, Modal, DeleteConfirm, ItemActions,
  Label, Input, Sel, Section, Field, StatCard, Textarea, VehicleSelect,
  fmtDate, fmtINR
} from '../Common/VehicleCommon';
import { TabContentShimmer, ErrorState } from '../Common/StateFeedback';

// ── Constants ─────────────────────────────────────────────────────────
const DOC_TYPES = ['RC', 'INSURANCE', 'PUC', 'FITNESS', 'PERMIT', 'TAX'];

const DOC_TYPE_COLORS = {
  RC: 'bg-blue-50 text-blue-600 border-blue-200',
  INSURANCE: 'bg-purple-50 text-purple-600 border-purple-200',
  PUC: 'bg-green-50 text-green-600 border-green-200',
  FITNESS: 'bg-orange-50 text-orange-600 border-orange-200',
  PERMIT: 'bg-teal-50 text-teal-600 border-teal-200',
  TAX: 'bg-pink-50 text-pink-600 border-pink-200',
};

// Help detect if a URL is one of our "fake" local ones
const isAutoGeneratedPath = (url) => typeof url === 'string' && url.includes('/temp_docs/');

// API returns status: VALID | EXPIRED | EXPIRING_SOON
const STATUS_STYLES = {
  VALID: { label: 'Valid', color: 'bg-green-50 text-green-600 border-green-200', dot: 'bg-green-500' },
  EXPIRED: { label: 'Expired', color: 'bg-red-50 text-red-600 border-red-200', dot: 'bg-red-500' },
  EXPIRING_SOON: { label: 'Expiring', color: 'bg-orange-50 text-orange-600 border-orange-200', dot: 'bg-orange-500' },
  RENEWED: { label: 'Renewed', color: 'bg-blue-50 text-blue-600 border-blue-200', dot: 'bg-blue-500' },
};

const EMPTY_FORM = {
  document_type: '',
  document_number: '',
  issue_date: '',
  expiry_date: '',
  issuing_authority: '',
  status: 'VALID',
  reminder_days_before_expiry: 30,
  notes: '',
  file_url: ''
};

const getDaysLeft = (date) => {
  if (!date) return null;
  const d = new Date(date);
  d.setHours(23, 59, 59, 999);
  const diff = d - new Date();
  return Math.ceil(diff / (1000 * 60 * 60 * 24));
};

// ── Field components ──────────────────────────────────────────────────

// ── Vehicle Searchable Dropdown ───────────────────────────────────────
// ──────────────────────────────────────────────────────────────────────

// ─── Detail View ─────────────────────────────────────────────────────────────
const DocDetailView = ({ data, onClose, onFileCached }) => {
  const st = STATUS_STYLES[data.status] ?? STATUS_STYLES.VALID;
  const [isOver, setIsOver] = useState(false);
  const [showPreview, setShowPreview] = useState(false);

  // Derived URL: Check Local Cache -> API
  let local_url = data.local_url;
  // If we don't have local_url in the object, check if the file_url points to a known local name
  if (!local_url && isAutoGeneratedPath(data.file_url)) {
    const filename = data.file_url.split('/').pop();
    // we can't easily access fileCache here without passing it, 
    // but data.local_url should have been injected by the parent.
  }
  
  // Predicted temp path based on ID (our manual "physical folder" trick)
  const predictedUrl = data.id ? `/temp_docs/${data.id.substring(0, 8)}.pdf` : null;
  
  const isLocal = !!local_url;
  // CRITICAL: We prefer local_url (Base64) > server file_url > predicted local path
  const finalUrl = local_url || data.file_url || predictedUrl;
  
  // Liberal check: show the file viewer if we have ANY lead on a file
  const hasFile = !!data.file_url || !!local_url || !!predictedUrl;

  const handleDrop = (e) => {
    e.preventDefault();
    setIsOver(false);
    const file = e.dataTransfer.files[0];
    if (file && onFileCached) {
      const reader = new FileReader();
      reader.onloadend = () => onFileCached(data.id, reader.result);
      reader.readAsDataURL(file);
    }
  };
  return (
    <div className="space-y-6 text-left">
      <div className="grid grid-cols-2 gap-6">
        <div>
          <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Document Type</p>
          <span className={`px-2 py-0.5 rounded-md text-[11px] font-bold border ${DOC_TYPE_COLORS[data.document_type] ?? 'bg-gray-50 text-gray-600 border-gray-200'}`}>
            {data.document_type}
          </span>
          {data.document_type_display && (
            <div className="text-[11px] text-gray-400 mt-0.5">{data.document_type_display}</div>
          )}
        </div>
        <div>
          <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Status</p>
          <span className={`flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-bold w-fit border ${st.color}`}>
            <span className={`w-1.5 h-1.5 rounded-full ${st.dot}`} />
            {st.label}
          </span>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-6">
        <div>
          <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Vehicle</p>
          <p className="text-sm font-bold text-[#172B4D] font-mono">
            {typeof data.vehicle === 'object'
              ? (data.vehicle?.registration_number ?? '—')
              : (data.vehicle_registration_number ?? data.vehicle_registration ?? data.vehicle_display ?? data.vehicle ?? '—')}
          </p>
        </div>
        <div>
          <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Document Number</p>
          <p className="text-sm font-black text-[#172B4D] font-mono">{data.document_number || '—'}</p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-6">
        <div>
          <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Issue Date</p>
          <p className="text-sm text-gray-600 font-semibold">{fmtDate(data.issue_date)}</p>
        </div>
        <div>
          <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Expiry Date</p>
          <p className="text-sm text-gray-600 font-semibold">{fmtDate(data.expiry_date)}</p>
          {data.expiry_date && (getDaysLeft(data.expiry_date) <= (data.reminder_days_before_expiry || 30)) && (
            <div className="flex items-center gap-1.5 mt-1.5 px-2 py-0.5 rounded-lg bg-red-50 border border-red-100 w-fit">
              <Clock size={10} className="text-red-500" />
              <p className="text-[10px] font-black text-red-600 uppercase tracking-tight">
                {getDaysLeft(data.expiry_date) < 0 
                  ? `${Math.abs(getDaysLeft(data.expiry_date))}d overdue` 
                  : `${getDaysLeft(data.expiry_date)}d left`}
              </p>
            </div>
          )}
        </div>
      </div>

      <div>
        <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Issuing Authority</p>
        <p className="text-sm text-gray-600 font-medium">{data.issuing_authority || '—'}</p>
      </div>

      <div>
        <p className="text-[10px] font-black text-gray-400 uppercase tracking-widest mb-1">Notes</p>
        <div className="p-3 rounded-xl bg-gray-50 border border-gray-100 min-h-[80px]">
          <p className="text-sm text-gray-600 whitespace-pre-wrap">{data.notes || 'No extra notes provided.'}</p>
        </div>
      </div>

      { hasFile ? (
        <div className="pt-4 border-t border-gray-100 mt-2">
          <p className="text-[10px] font-black text-blue-500 uppercase tracking-widest mb-3">
            {local_url ? 'Local Session Attachment' : data.file_url ? 'Verified Attachment' : 'Local File Found (Predicted)'}
          </p>
          <button
            onClick={() => setShowPreview(!showPreview)}
            className="flex items-center gap-4 p-4 rounded-2xl bg-gradient-to-br from-white to-blue-50 border border-blue-100 shadow-sm hover:shadow-md hover:border-blue-300 transition-all group w-full text-left"
          >
            <div className="w-12 h-12 rounded-xl bg-[#0052CC] text-white flex items-center justify-center shadow-lg shadow-blue-200 group-hover:scale-110 transition-transform duration-300">
              <Eye size={20} />
            </div>
            <div className="flex flex-col flex-1">
              <span className="text-sm font-black text-[#172B4D] tracking-tight">
                {showPreview ? 'Hide Document Preview' : 'Preview Document Inline'}
              </span>
              <span className="text-[11px] font-bold text-blue-500 uppercase tracking-tighter">
                {isLocal ? 'Using browser persistent storage' : 'Using secure server link'}
              </span>
            </div>
            <div className="w-8 h-8 rounded-lg bg-blue-100/50 flex items-center justify-center text-[#0052CC] group-hover:bg-[#0052CC] group-hover:text-white transition-colors">
              <ChevronDown size={14} className={`transition-transform duration-300 ${showPreview ? 'rotate-180' : ''}`} />
            </div>
          </button>
          
          {showPreview && (
            <div className="mt-4 rounded-2xl border border-gray-100 overflow-hidden bg-gray-900 shadow-inner">
              <div className="p-2 bg-gray-800 flex justify-between items-center">
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest pl-2">Secure Local Preview</span>
                <a 
                  href={finalUrl} 
                  download 
                  className="text-[10px] font-black text-blue-400 hover:text-blue-300 uppercase tracking-widest flex items-center gap-1 px-3 py-1 rounded-lg bg-blue-500/10"
                >
                  <Download size={10} /> Download
                </a>
              </div>
              <div className="max-h-[400px] overflow-auto flex items-center justify-center bg-gray-900/50 p-4">
                {finalUrl?.startsWith('data:image') || finalUrl?.match(/\.(webp|jpg|jpeg|png|gif)$/i) ? (
                  <img src={finalUrl} alt="Document" className="max-w-full h-auto rounded shadow-2xl" />
                ) : (
                  <iframe src={finalUrl} className="w-full h-[380px] border-none bg-white rounded shadow-2xl" title="PDF Preview" />
                )}
              </div>
            </div>
          )}
          {isLocal && (
            <p className="mt-2 text-[10px] text-gray-400 italic">
              Note: This file is stored in your browser. To make it permanent for others, please upload to the backend once fixed.
            </p>
          )}
        </div>
      ) : (
        <div 
          onDragOver={(e) => { e.preventDefault(); setIsOver(true); }}
          onDragLeave={() => setIsOver(false)}
          onDrop={handleDrop}
          className={`mt-4 p-6 rounded-2xl border-2 border-dashed transition-all duration-300 text-center
            ${isOver ? 'bg-blue-50 border-blue-400 scale-[1.02]' : 'bg-gray-50 border-gray-200'}`}
        >
          <div className="w-10 h-10 rounded-full bg-white shadow-sm flex items-center justify-center mx-auto mb-3 text-gray-400">
            <Upload size={18} />
          </div>
          <p className="text-xs font-bold text-gray-500">No file attached to this record.</p>
          <p className="text-[10px] text-gray-400 mt-1">Drop a file here to save it locally in your "Temporary Folder".</p>
          
          <div className="mt-4 flex items-center justify-center gap-2">
            <div className="h-px bg-gray-200 flex-1" />
            <span className="text-[9px] font-black text-gray-300 uppercase tracking-widest">Or use physical folder</span>
            <div className="h-px bg-gray-200 flex-1" />
          </div>
          <p className="text-[10px] text-gray-400 mt-2">
            Save to <code className="bg-gray-100 px-1 rounded text-blue-500">public/temp_docs/{data.id.substring(0,8)}.pdf</code>
          </p>
        </div>
      )}

      <div className="pt-4 border-t border-gray-100 flex justify-end gap-3">
        <button onClick={onClose} className="px-4 py-2 text-sm font-bold text-[#0052CC] bg-blue-50 rounded-xl hover:bg-blue-100 transition-all">
          Close
        </button>
      </div>
    </div>
  );
};

// ── Add / Edit Modal ──────────────────────────────────────────────────
const DocModal = ({ initial, onClose, isView, vehicleId, onDeleteRequest, onFileCached }) => {
  // Force browser reload comment: v3
  const [localError, setLocalError] = useState(null);
  const isEdit = !!initial?.id && !isView;
  console.log('DocModal Debug:', { initial, vehicleId, isEdit });

  // FETCH FULL DATA IF EDIT (to get missing vehicle ID from the list response)
  const { data: fullData } = useVehicleDocument(initial?.id, {
    enabled: isEdit && !vehicleId && (!initial?.vehicle || typeof initial?.vehicle !== 'object'),
    expand: 'vehicle'
  });

  // Backup: Manual mapping via vehicle list
  const { data: vData } = useVehicles({ all: true }, { enabled: isEdit && !vehicleId });
  const allVehicles = vData?.results ?? vData ?? [];

  const resolveVehicleId = () => {
    if (vehicleId) return vehicleId;
    if (typeof initial?.vehicle === 'object' && initial.vehicle !== null) return initial.vehicle.id || '';
    if (initial?.vehicle_id) return initial.vehicle_id;
    
    // Attempt manual match by registration string
    const reg = initial?.vehicle_registration_number || initial?.vehicle_registration || initial?.vehicle || '';
    if (reg && allVehicles.length > 0) {
      const norm = (s) => String(s || '').replace(/\s+/g, '').toUpperCase();
      const match = allVehicles.find(v => norm(v.registration_number) === norm(reg));
      if (match) return match.id;
    }
    return '';
  };

  const [form, setForm] = useState(
    initial ? {
      vehicle: resolveVehicleId(),
      document_type: initial.document_type ?? '',
      document_number: initial.document_number ?? '',
      issue_date: initial.issue_date ?? '',
      expiry_date: initial.expiry_date ?? '',
      issuing_authority: initial.issuing_authority ?? '',
      status: initial.status ?? 'VALID',
      notes: initial.notes ?? '',
      file_url: initial.file_url ?? '',
      document: null,
    } : { ...EMPTY_FORM, vehicle: vehicleId ?? '' }
);

  // Dynamic URL Generation: Update file_url when document is selected
  useEffect(() => {
    if (form.document && !form.file_url) {
      // Clean filename for URL and make it absolute to pass backend validation
      const cleanName = form.document.name.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9._-]/g, '');
      const absoluteUrl = `${window.location.origin}/temp_docs/${cleanName}`;
      set('file_url')({ target: { value: absoluteUrl } });
    }
  }, [form.document]);

  const create = useCreateVehicleDocument();
  const update = useUpdateVehicleDocument();
  const isPending = create.isPending || update.isPending;
  const [errors, setErrors] = useState({});
  const set = (f) => (e) => setForm(p => ({ ...p, [f]: e.target.value }));

  // Sync vehicle ID when full data or vehicle list is fetched
  useEffect(() => {
    if (isEdit && !form.vehicle && allVehicles.length > 0) {
      const reg = initial?.vehicle_registration_number || initial?.vehicle_registration || initial?.vehicle || '';
      if (reg) {
        const norm = (s) => String(s || '').replace(/\s+/g, '').toUpperCase();
        const match = allVehicles.find(v => norm(v.registration_number) === norm(reg));
        if (match) setForm(p => ({ ...p, vehicle: match.id }));
      }
    }
    if (fullData) {
      const vId = fullData.vehicle?.id || fullData.vehicle || fullData.vehicle_id || '';
      if (vId && !form.vehicle) {
        setForm(p => ({ ...p, vehicle: vId }));
      }
    }
  }, [allVehicles, fullData, isEdit, initial, form.vehicle]);

  // Real-time date validation
  useEffect(() => {
    if (form.issue_date && form.expiry_date) {
      if (new Date(form.expiry_date) <= new Date(form.issue_date)) {
        setErrors(prev => ({ ...prev, expiry_date: 'Expiry must be after issue date' }));
      } else {
        setErrors(prev => {
          const { expiry_date, ...rest } = prev;
          return rest;
        });
      }
    } else {
       setErrors(prev => {
          const { expiry_date, ...rest } = prev;
          return rest;
        });
    }
  }, [form.issue_date, form.expiry_date]);

  const handleSubmit = () => {
    if (Object.keys(errors).length > 0) return;

    const clean = Object.fromEntries(Object.entries(form).map(([k, v]) => [k, v === '' ? null : v]));
    
    // Use FormData for file upload
    const formData = new FormData();
    Object.entries(clean).forEach(([k, v]) => {
      if (v !== null && v !== undefined) {
        if (k === 'document') {
          // Send in both fields for maximum compatibility
          formData.append('document', v);
          formData.append('file', v);
        } else {
          formData.append(k, v);
        }
      }
    });

    const handleSuccess = (res) => {
      setLocalError(null);
      console.log('Upload Success Response:', res);
      if (form.document && res?.id) {
        // Use FileReader to get Base64 for persistence
        const reader = new FileReader();
        reader.onloadend = () => {
          const base64 = reader.result;
          const cleanName = form.document.name.replace(/\s+/g, '_').replace(/[^a-zA-Z0-9._-]/g, '');
          console.log('Caching file (Base64) for ID:', res.id, 'and Name:', cleanName);
          onFileCached(res.id, base64);
          onFileCached(cleanName, base64); // Redundant storage by name
          onClose();
        };
        reader.readAsDataURL(form.document);
      } else {
        onClose();
      }
    };

    const handleError = (err) => {
      const msg = parseError(err);
      setLocalError(msg);
    };

    console.log('Submitting FormData:', Array.from(formData.entries()));
    if (isEdit) update.mutate({ id: initial.id, data: formData }, { onSuccess: handleSuccess, onError: handleError });
    else create.mutate(formData, { onSuccess: handleSuccess, onError: handleError });
  };

  return (
    <Modal
      title={isView ? 'Document Details' : isEdit ? 'Edit Document' : 'Add Document'}
      onClose={onClose}
      onSubmit={handleSubmit}
      submitting={isPending}
      submitDisabled={Object.keys(errors).length > 0}
      isView={isView}
      onDelete={isEdit ? onDeleteRequest : null}
    >
      <div className="space-y-4">
        {!isView && localError && (
          <div className="p-4 rounded-xl bg-red-50 border border-red-100 flex items-start gap-3 animate-in fade-in slide-in-from-top-2 duration-300">
            <AlertCircle className="text-red-500 mt-0.5 shrink-0" size={18} />
            <div className="flex-1">
              <p className="text-sm font-bold text-red-900 leading-tight">Validation Error</p>
              <p className="text-xs text-red-700 font-medium mt-1 leading-relaxed">{localError}</p>
            </div>
          </div>
        )}
        {isView ? (
          <DocDetailView data={initial} onClose={onClose} onFileCached={onFileCached} />
        ) : (
          <>
            {!vehicleId && (
              <Field label="Vehicle" required={!isEdit}>
                <VehicleSelect
                  value={form.vehicle}
                  disabled={isEdit}
                  placeholder={initial?.vehicle_registration_number || initial?.vehicle_registration || initial?.vehicle_display}
                  onChange={(id) => setForm(p => ({ ...p, vehicle: id }))}
                />
                {isEdit && !form.vehicle && (
                  <p className="text-[11px] text-orange-500 mt-1"></p>
                )}
              </Field>
            )}
            <div className="grid grid-cols-2 gap-4">
              <Field label="Document Type" required>
                <Sel value={form.document_type} onChange={set('document_type')}>
                  <option value="">Select type</option>
                  {DOC_TYPES.map(d => <option key={d} value={d}>{d}</option>)}
                </Sel>
              </Field>
              <Field label="Document Number" required>
                <Input placeholder="e.g. RCMH12AB1234" value={form.document_number} onChange={set('document_number')} />
              </Field>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <Field label="Issue Date"><Input type="date" value={form.issue_date} onChange={set('issue_date')} /></Field>
              <Field label="Expiry Date" error={errors.expiry_date}><Input type="date" value={form.expiry_date} onChange={set('expiry_date')} /></Field>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <Field label="Issuing Authority"><Input placeholder="e.g. RTO Mumbai" value={form.issuing_authority} onChange={set('issuing_authority')} /></Field>
              <Field label="Status">
                <Sel value={form.status} onChange={set('status')}>
                  <option value="VALID">Valid</option>
                  <option value="EXPIRED">Expired</option>
                  <option value="RENEWED">Renewed</option>
                </Sel>
              </Field>
            </div>
            <div className="pt-2 border-t border-gray-100 mt-4">
              <p className="text-[11px] font-black text-blue-500 uppercase tracking-[0.2em] mb-4">Documentation & Links</p>
              
              <div className="space-y-4">
                <Field label="File URL (Persistent Link)">
                  <div className="relative group/link">
                    <ExternalLink size={14} className="absolute left-3 top-3 text-gray-400 group-focus-within/link:text-[#0052CC] transition-colors" />
                    <input 
                      type="text" 
                      placeholder="https://example.com/files/document.pdf" 
                      value={form.file_url} 
                      onChange={set('file_url')}
                      className="w-full pl-10 pr-4 py-2.5 rounded-xl border border-gray-200 bg-gray-50 text-sm font-medium focus:outline-none focus:ring-2 focus:ring-[#0052CC]/10 focus:border-[#0052CC] transition-all"
                    />
                  </div>
                </Field>

                <div className="flex items-center gap-3 py-1">
                  <div className="h-px bg-gray-200 flex-1" />
                  <span className="text-[10px] font-black text-gray-300 uppercase tracking-widest px-2">OR UPLOAD NEW FILE</span>
                  <div className="h-px bg-gray-200 flex-1" />
                </div>

                <Field label="Upload File (PDF, Image)">
                  <div className="relative group/file">
                    <input
                      type="file"
                      onChange={(e) => {
                        const file = e.target.files[0];
                        if (file) setForm(p => ({ ...p, document: file }));
                      }}
                      className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10"
                      accept=".pdf,image/*"
                    />
                    
                    <div className={`w-full overflow-hidden rounded-2xl border-2 transition-all duration-300 flex flex-col
                      ${form.document 
                        ? 'bg-blue-50/30 border-blue-200/50 shadow-sm shadow-blue-100' 
                        : 'bg-gray-50/50 border-dashed border-gray-200 hover:border-blue-400/50 hover:bg-blue-50/10 hover:shadow-lg hover:shadow-blue-50/50 group-hover/file:-translate-y-0.5'}`}>
                      
                      <div className="p-4 flex items-center gap-4">
                        <div className={`w-12 h-12 rounded-xl flex items-center justify-center transition-all duration-500 shadow-sm
                          ${form.document 
                            ? 'bg-gradient-to-br from-blue-500 to-[#0052CC] text-white scale-110 shadow-blue-200' 
                            : 'bg-white text-gray-400 group-hover/file:text-[#0052CC] group-hover/file:scale-110 group-hover/file:shadow-md'}`}>
                          {form.document ? <CheckCircle size={24} className="animate-in zoom-in duration-300" /> : <Upload size={24} />}
                        </div>
                        
                        <div className="flex-1 min-w-0">
                          <p className={`text-sm font-black tracking-tight truncate ${form.document ? 'text-[#0052CC]' : 'text-[#172B4D]'}`}>
                            {form.document ? form.document.name : 'Choose document or drag here'}
                          </p>
                          <p className="text-[10px] font-bold text-gray-400 uppercase tracking-widest mt-0.5">
                            {form.document 
                              ? `${(form.document.size / (1024 * 1024)).toFixed(2)} MB • ${form.document.type.split('/')[1].toUpperCase()}` 
                              : 'PDF, JPG, PNG • Max 5MB'}
                          </p>
                        </div>

                        {form.document ? (
                          <button
                            type="button"
                            onClick={(e) => { e.preventDefault(); e.stopPropagation(); setForm(p => ({ ...p, document: null })); }}
                            className="p-2 hover:bg-red-50 text-gray-300 hover:text-red-500 rounded-lg transition-all relative z-20 group/remove"
                            title="Remove file"
                          >
                            <X size={18} className="group-hover/remove:rotate-90 transition-transform duration-300" />
                          </button>
                        ) : (
                          <div className="px-3 py-1.5 bg-white border border-gray-200 rounded-lg text-[11px] font-black text-[#0052CC] shadow-sm uppercase tracking-tighter group-hover/file:bg-blue-50 transition-colors">
                            Browse
                          </div>
                        )}
                      </div>

                      {form.document && (
                        <div className="h-1 w-full bg-blue-100/50 relative overflow-hidden">
                          <div className="absolute inset-0 bg-gradient-to-r from-blue-400 to-blue-600 w-full animate-in slide-in-from-left duration-700" />
                        </div>
                      )}
                    </div>
                  </div>
                </Field>

                <Field label="Notes">
                  <Textarea value={form.notes ?? ''} onChange={set('notes')} rows={2} placeholder="Any additional notes..." />
                </Field>
              </div>
            </div>
          </>
        )}
      </div>
    </Modal>
  );
};


// ── Main Page ─────────────────────────────────────────────────────────
const VehicleDocuments = ({ vehicleId, isTab }) => {
  const [search, setSearch] = useState('');
  const [typeFilter, setType] = useState('');
  const [modal, setModal] = useState(null);
  const [viewTarget, setView] = useState(null);
  const [deleteTarget, setDelete] = useState(null);
  const [currentPage, setCurrentPage] = useState(1);
  const [showAlertModal, setShowAlertModal] = useState(false);
  
  // Persistent file cache using localStorage
  const [fileCache, setFileCache] = useState(() => {
    try {
      const saved = localStorage.getItem('vehicle_doc_cache');
      return saved ? JSON.parse(saved) : {};
    } catch (e) {
      return {};
    }
  });

  // Sync cache to localStorage
  useEffect(() => {
    localStorage.setItem('vehicle_doc_cache', JSON.stringify(fileCache));
  }, [fileCache]);

  const del = useDeleteVehicleDocument();

  const { data, isLoading, isError, error, refetch } = useVehicleDocuments({
    ...(vehicleId && { vehicle: vehicleId }),
    ...(typeFilter && { document_type: typeFilter }),
    ...(search && { search }),
    expand: 'vehicle',
    page: currentPage,
  });

  const docsRaw = data?.results ?? data ?? [];
  const docs = docsRaw.map(d => {
    // Try to find in cache by ID or by Filename extracted from the URL
    let local_url = fileCache[d.id];
    if (!local_url && d.file_url) {
      const filename = d.file_url.split('/').pop();
      local_url = fileCache[filename];
    }
    return { ...d, local_url };
  });
  const total = data?.count ?? docs.length;
  // Use API status field directly
  const valid = docs.filter(d => d.status === 'VALID').length;
  const expiring = docs.filter(d => d.status === 'EXPIRING_SOON').length;
  const expired = docs.filter(d => d.status === 'EXPIRED').length;

  // Auto-show modal if there are expired or expiring documents (only on first load with data)
  useEffect(() => {
    if ((expired > 0 || expiring > 0) && !isLoading) {
      setShowAlertModal(true);
    }
  }, [expired, expiring, isLoading]);

  const content = (
    <div className={`flex flex-col h-full ${isTab ? '' : 'p-6 bg-[#f8fafc] flex-1 min-h-0 overflow-hidden relative font-sans text-slate-900'}`}>

      {(modal === 'add' || (modal && modal !== 'add')) && (
        <DocModal 
          vehicleId={vehicleId} 
          initial={modal === 'add' ? null : modal} 
          onClose={() => setModal(null)} 
          onDeleteRequest={() => { setModal(null); setDelete(modal); }} 
          onFileCached={(id, url) => setFileCache(p => ({ ...p, [id]: url }))}
        />
      )}
      {viewTarget && (
        <DocModal 
          vehicleId={vehicleId} 
          initial={viewTarget} 
          isView 
          onClose={() => setView(null)} 
        />
      )}
      {deleteTarget && (
        <DeleteConfirm label="Document" onClose={() => setDelete(null)}
          onConfirm={() => del.mutate(deleteTarget.id, { onSuccess: () => setDelete(null) })}
          deleting={del.isPending} />
      )}

      {showAlertModal && (
        <Modal
          title="Compliance & Renewal Alerts"
          onClose={() => setShowAlertModal(false)}
          maxWidth="max-w-4xl"
          isView
        >
          <div className="space-y-4">
            <div className={`flex items-center gap-3 p-4 rounded-2xl border ${expired > 0 ? 'bg-red-50 border-red-100 text-red-700' : 'bg-orange-50 border-orange-100 text-orange-700'}`}>
              {expired > 0 ? <AlertCircle size={24} className="shrink-0 animate-pulse" /> : <Clock size={24} className="shrink-0 animate-bounce" />}
              <div>
                <p className="font-black text-sm uppercase tracking-tight">
                  {expired > 0 ? 'Critical Expirations Detected' : 'Upcoming Renewals Needed'}
                </p>
                <p className="text-xs font-bold opacity-80">
                  {expired > 0
                    ? `You have ${expired} expired documents. Please renew them immediately to avoid legal and operational issues.`
                    : `You have ${expiring} documents expiring soon. Please plan their renewal to ensure continuous compliance.`
                  }
                </p>
              </div>
            </div>

            <div className="overflow-hidden border border-gray-100 rounded-2xl shadow-sm">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-gray-50 border-b border-gray-100 text-[10px] font-black text-gray-400 uppercase tracking-widest">
                    <th className="px-4 py-3 text-left">Vehicle</th>
                    <th className="px-4 py-3 text-left">Doc Type</th>
                    <th className="px-4 py-3 text-left">Expiry Date</th>
                    <th className="px-4 py-3 text-left">Status</th>
                    <th className="px-4 py-3 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-50">
                  {docs
                    .filter(d => d.status === 'EXPIRED' || d.status === 'EXPIRING_SOON')
                    .sort((a, b) => a.status === 'EXPIRED' ? -1 : 1)
                    .map(d => (
                      <tr key={d.id} className={`hover:bg-gray-50/50 transition-colors ${d.status === 'EXPIRED' ? 'bg-red-50/20' : ''}`}>
                        <td className="px-4 py-3 font-mono font-bold text-[#172B4D] uppercase">
                          {typeof d.vehicle === 'object' ? d.vehicle?.registration_number : d.vehicle_registration_number || d.vehicle_display}
                        </td>
                        <td className="px-4 py-3">
                          <span className={`px-2 py-0.5 rounded-md text-[10px] font-black border ${DOC_TYPE_COLORS[d.document_type]}`}>
                            {d.document_type}
                          </span>
                        </td>
                        <td className={`px-4 py-3 font-bold text-xs ${d.status === 'EXPIRED' ? 'text-red-600' : 'text-orange-600'}`}>
                          {fmtDate(d.expiry_date)}
                        </td>
                        <td className="px-4 py-3">
                          <Badge className={STATUS_STYLES[d.status].color}>
                            <span className={`w-1 h-1 rounded-full ${STATUS_STYLES[d.status].dot}`} />
                            {STATUS_STYLES[d.status].label}
                          </Badge>
                        </td>
                        <td className="px-4 py-3 text-right">
                          <button
                            onClick={() => { setShowAlertModal(false); setModal(d); }}
                            className="px-3 py-1 bg-white border border-gray-200 rounded-lg text-[11px] font-bold text-[#0052CC] hover:bg-blue-50 transition-all shadow-sm"
                          >
                            Edit / Renew
                          </button>
                        </td>
                      </tr>
                    ))}
                </tbody>
              </table>
            </div>

            <div className="flex justify-end pt-2">
              <button
                onClick={() => setShowAlertModal(false)}
                className="px-6 py-2 bg-gray-100 text-gray-600 rounded-xl text-sm font-bold hover:bg-gray-200 transition-all shadow-md active:scale-95"
              >
                Dismiss Alerts
              </button>
            </div>
          </div>
        </Modal>
      )}

      {/* Header — hidden in tab mode */}
      {!isTab && (
        <div className="flex items-center mb-8">
          <div className="w-1/4">
            <h2 className="text-2xl font-bold text-[#172B4D]">Documents</h2>
            <p className="text-gray-500 text-sm tracking-tight">RC, Insurance, PUC, Fitness</p>
          </div>

          <div className="flex-1 max-w-2xl px-8">
            <div className="relative group/search">
              <Search className="absolute left-4 top-3.5 text-gray-400 group-focus-within/search:text-[#0052CC] transition-all duration-300 group-focus-within/search:scale-110" size={20} />
              <input
                type="text"
                placeholder="Search number..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="w-full pl-12 pr-12 py-3 bg-white border border-gray-200 rounded-2xl text-[15px] font-medium placeholder:text-gray-400 focus:outline-none focus:ring-4 focus:ring-blue-50 transition-all shadow-sm hover:shadow-md hover:border-gray-300"
              />
              {search && (
                <button
                  onClick={() => setSearch('')}
                  className="absolute right-4 top-2 text-gray-400 hover:text-red-500 transition-all duration-500 hover:rotate-180 p-1.5 rounded-full hover:bg-red-50 flex items-center justify-center group/reset"
                  title="Clear search"
                >
                  <RotateCcw size={18} className="animate-in fade-in zoom-in spin-in-180 duration-500 group-hover/reset:scale-110" />
                </button>
              )}
            </div>
          </div>

          <div className="flex items-center justify-end gap-2 ml-auto">
            <div className="flex items-center gap-2 mr-2">
              <button
                onClick={() => refetch()}
                className="flex items-center gap-2 px-3 py-2 bg-[#EBF3FF] text-[#0052CC] hover:bg-[#0052CC] hover:text-white rounded-xl transition-all duration-300 font-bold text-xs shadow-sm active:scale-95 group"
              >
                <RotateCcw size={14} className={isLoading ? "animate-spin" : "group-hover:rotate-180 transition-transform duration-500"} />
                <span>Refresh</span>
              </button>
              <button className="flex items-center gap-2 px-3 py-2 bg-[#EBF3FF] text-[#0052CC] hover:bg-[#0052CC] hover:text-white rounded-xl transition-all duration-300 font-bold text-xs shadow-sm active:scale-95">
                <Download size={14} />
                <span>Export</span>
              </button>
              <button className="flex items-center gap-2 px-3 py-2 bg-[#EBF3FF] text-[#0052CC] hover:bg-[#0052CC] hover:text-white rounded-xl transition-all duration-300 font-bold text-xs shadow-sm active:scale-95">
                <Upload size={14} />
                <span>Import</span>
              </button>
            </div>
            <div className="w-px h-8 bg-gray-200 mx-1" />
          </div>
        </div>
      )}

      {/* Table / List Card */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-100 flex-1 flex flex-col min-h-0 overflow-hidden mt-2">
        {/* Compact Stats Row */}
        <div className="flex items-center gap-8 px-5 py-4 border-b border-gray-100 bg-gray-50/50">
          {isLoading ? (
            <div className="flex gap-6 animate-pulse">
              <div className="h-5 bg-gray-200 rounded w-24"></div>
              <div className="h-5 bg-gray-200 rounded w-24"></div>
              <div className="h-5 bg-gray-200 rounded w-24"></div>
              <div className="h-5 bg-gray-200 rounded w-24"></div>
            </div>
          ) : (
            <>
              <div className="flex items-center gap-2">
                <span className="text-[13px] font-bold text-gray-500 uppercase tracking-wider">Total:</span>
                <span className="text-[18px] font-black text-[#172B4D]">{total}</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="text-[13px] font-bold text-gray-500 uppercase tracking-wider">Valid:</span>
                <span className="text-[18px] font-black text-emerald-600">{valid}</span>
              </div>
              <div
                className={`flex items-center gap-2 transition-all duration-300 p-2 rounded-xl ${expiring > 0 ? 'bg-orange-50/50 cursor-pointer hover:bg-orange-100/80 hover:scale-105 shadow-sm shadow-orange-100 group/expiring' : ''}`}
                onClick={() => expiring > 0 && setShowAlertModal(true)}
                title={expiring > 0 ? "Click to view upcoming renewals" : ""}
              >
                <span className="text-[13px] font-bold text-gray-500 uppercase tracking-wider group-hover/expiring:text-orange-700">Expiring:</span>
                <span className={`text-[18px] font-black ${expiring > 0 ? 'text-orange-500 animate-pulse' : 'text-orange-500'}`}>{expiring}</span>
                {expiring > 0 && <Clock size={14} className="text-orange-500 animate-spin-slow" />}
              </div>
              <div
                className={`flex items-center gap-2 transition-all duration-300 p-2 rounded-xl ${expired > 0 ? 'bg-red-50/50 cursor-pointer hover:bg-red-100/80 hover:scale-105 shadow-sm shadow-red-100 group/expired' : ''}`}
                onClick={() => expired > 0 && setShowAlertModal(true)}
                title={expired > 0 ? "Click to view expired documents" : ""}
              >
                <span className="text-[13px] font-bold text-gray-500 uppercase tracking-wider group-hover/expired:text-red-700">Expired:</span>
                <span className={`text-[18px] font-black ${expired > 0 ? 'text-red-600 animate-pulse' : 'text-red-600'}`}>{expired}</span>
                {expired > 0 && <AlertCircle size={14} className="text-red-500 animate-bounce" />}
              </div>
            </>
          )}
          <div className="ml-auto w-1/4 flex justify-end">
            <button
              onClick={() => setModal('add')}
              className="mr-0 bg-[#0052CC] text-white px-6 py-3 rounded-xl flex items-center gap-2 text-sm font-bold hover:bg-[#0747A6] transition-all shadow-lg hover:shadow-blue-200 active:scale-95 group"
            >
              <Plus size={20} className="group-hover:rotate-90 transition-transform duration-300" />
              <span>Add Document</span>
            </button>
          </div>
        </div>


        <div>
          {/* Filters & Pagination Row */}
          <div className="flex items-center justify-between px-5 py-3 bg-white border-b border-gray-50 h-[60px]">
            <div className="flex items-center gap-6">
              {isTab && (
                <div className="relative w-64 text-gray-400">
                  <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2" />
                  <input
                    type="text"
                    placeholder="Search number..."
                    className="w-full pl-9 pr-3 py-2 text-sm bg-gray-50 border-none rounded-lg focus:ring-2 focus:ring-[#0052CC]/10 text-[#172B4D] font-medium"
                    value={search}
                    onChange={e => setSearch(e.target.value)}
                  />
                  {search && (
                    <button onClick={() => setSearch('')} className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-red-500">
                      <X size={14} />
                    </button>
                  )}
                </div>
              )}
              <div className="relative">
                <select
                  value={typeFilter}
                  onChange={e => setType(e.target.value)}
                  className="appearance-none pl-3 pr-8 py-1.5 bg-gray-50 border border-gray-200 rounded-lg text-[12px] font-bold text-[#172B4D] focus:outline-none focus:ring-2 focus:ring-blue-100 transition-all hover:border-gray-200 cursor-pointer shadow-sm"
                >
                  <option value="">All Types</option>
                  {DOC_TYPES.map(o => <option key={o} value={o}>{o}</option>)}
                </select>
                <ChevronDown size={13} className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 pointer-events-none" />
              </div>
              {typeFilter && (
                <button
                  onClick={() => setType('')}
                  className="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-all"
                  title="Clear Filters"
                >
                  <RotateCcw size={14} />
                </button>
              )}
            </div>

            {!isTab && (
              <div className="flex items-center gap-3">
                <button
                  onClick={() => setCurrentPage(prev => Math.max(1, prev - 1))}
                  disabled={currentPage === 1 || isLoading}
                  className="px-4 py-1.5 text-xs font-bold bg-white border border-gray-200 rounded-lg text-[#172B4D] hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-sm flex items-center gap-2"
                >
                  Previous
                </button>

                <div className="flex items-center justify-center min-w-8 h-8 bg-[#0052CC] text-white rounded-lg text-xs font-bold shadow-md shadow-blue-100">
                  {currentPage}
                </div>

                <button
                  onClick={() => setCurrentPage(prev => prev + 1)}
                  disabled={!data?.next || isLoading}
                  className="px-4 py-1.5 text-xs font-bold bg-white border border-gray-200 rounded-lg text-[#172B4D] hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-sm flex items-center gap-2"
                >
                  Next
                </button>
              </div>
            )}
          </div>
        </div>

        {isLoading && <TabContentShimmer />}

        {isError && <ErrorState message="Failed to load documents" error={error?.message} onRetry={() => refetch()} />}

        {!isLoading && !isError && (
          <div className="flex-1 overflow-auto min-h-0">
            <table className="w-full text-sm relative">
              <thead>
                <tr className="bg-gray-50 border-b border-gray-100 sticky top-0 z-10">
                  {!vehicleId && <th className="text-left px-4 py-3 text-[11px] font-bold text-gray-400 uppercase tracking-widest whitespace-nowrap">Vehicle</th>}
                  {['Doc Type', 'Doc Number', 'Expiry Date', 'Status', 'File', 'Actions'].map(h => (
                    <th key={h} className="text-left px-4 py-3 text-[11px] font-bold text-gray-400 uppercase tracking-widest whitespace-nowrap">{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {docs.map(doc => {
                  const st = STATUS_STYLES[doc.status] ?? STATUS_STYLES.VALID;
                  return (
                    <tr key={doc.id} className="hover:bg-blue-50/30 transition-colors cursor-pointer" onClick={() => setView(doc)}>

                      {/* Vehicle — hidden if vehicleId is prop */}
                      {!vehicleId && (
                        <td className="px-4 py-3 whitespace-nowrap">
                          <button onClick={() => setView(doc)}
                            className="font-bold text-[#172B4D] font-mono text-[13px] hover:text-[#0052CC] transition-all text-left uppercase hover:underline decoration-blue-400/30 underline-offset-4">
                            {typeof doc.vehicle === 'object'
                              ? (doc.vehicle?.registration_number ?? '—')
                              : (doc.vehicle_registration_number ?? doc.vehicle_registration ?? doc.vehicle_display ?? doc.vehicle ?? '—')}
                          </button>
                        </td>
                      )}

                      {/* Doc Type */}
                      <td className="px-4 py-3 whitespace-nowrap">
                        <div>
                          <span className={`px-2 py-0.5 rounded-md text-[11px] font-bold border ${DOC_TYPE_COLORS[doc.document_type] ?? 'bg-gray-50 text-gray-600 border-gray-200'}`}>
                            {doc.document_type}
                          </span>
                          {doc.document_type_display && (
                            <div className="text-[11px] text-gray-400 mt-0.5">{doc.document_type_display}</div>
                          )}
                        </div>
                      </td>

                      {/* Doc Number */}
                      <td className="px-4 py-3 whitespace-nowrap">
                        <span className="font-mono font-bold text-[#172B4D] text-[13px]">{doc.document_number ?? '—'}</span>
                      </td>

                      {/* Expiry Date */}
                      <td className="px-4 py-3 whitespace-nowrap">
                        <div className="flex flex-col">
                          <span className="text-sm text-gray-600 font-semibold">{fmtDate(doc.expiry_date)}</span>
                          {doc.expiry_date && (getDaysLeft(doc.expiry_date) <= (doc.reminder_days_before_expiry || 30)) && (
                            <span className="text-[10px] font-bold text-red-500 mt-0.5">
                              {getDaysLeft(doc.expiry_date) < 0 
                                ? `${Math.abs(getDaysLeft(doc.expiry_date))}d overdue` 
                                : `${getDaysLeft(doc.expiry_date)}d left`}
                            </span>
                          )}
                        </div>
                      </td>

                      {/* Status — from API directly */}
                      <td className="px-4 py-3 whitespace-nowrap">
                        <Badge className={st.color}>
                          <span className={`w-1.5 h-1.5 rounded-full ${st.dot}`} />
                          {st.label}
                        </Badge>
                      </td>

                      {/* File */}
                      <td className="px-4 py-3 whitespace-nowrap">
                        { (doc.local_url || doc.file_url) ? (
                          <a
                            href={doc.local_url || doc.file_url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className={`p-1.5 rounded-lg transition-all flex items-center justify-center w-fit ${doc.file_url ? 'bg-blue-50 text-[#0052CC] hover:bg-blue-100' : 'bg-orange-50 text-orange-600 hover:bg-orange-100'}`}
                            title={doc.local_url ? "View Local Copy" : "View Document"}
                            onClick={(e) => e.stopPropagation()}
                          >
                            <FileText size={14} />
                          </a>
                        ) : (
                          <span className="text-gray-300">—</span>
                        )}
                      </td>

                      {/* Actions */}
                      <td className="px-4 py-3 whitespace-nowrap">
                        <div className="flex items-center gap-2">
                          <button onClick={(e) => { e.stopPropagation(); setModal(doc); }}
                            className="flex items-center gap-1 px-3 py-1.5 text-[12px] font-semibold text-[#0052CC] bg-blue-50 border border-blue-200 rounded-lg hover:bg-blue-100">
                            <Pencil size={12} /> Edit
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
                {docs.length === 0 && (
                  <tr><td colSpan={8} className="px-4 py-16 text-center text-gray-400">
                    <FileText size={32} className="mx-auto mb-2 opacity-30" /><p className="text-sm">No documents found</p>
                  </td></tr>
                )}
              </tbody>
            </table>
          </div>
        )}

        {!isTab && !isLoading && !isError && (
          <div className="px-5 py-3 border-t border-gray-100 flex items-center justify-between text-xs text-gray-400">
            <span>Showing <span className="font-bold text-gray-600">{docs.length}</span>{data?.count && data.count !== docs.length && <> of <span className="font-bold text-gray-600">{data.count}</span></>} documents</span>
            {!isTab && <span className="text-[11px]">Fleet Management System</span>}
          </div>
        )}
      </div>
    </div>
  );

  return content;
};

export default VehicleDocuments;
